### ISSUE TITLE
What do the outputs correspond to depending on the model

### ISSUE THREAD

**Issue by olayasturias** [ImperialCollegeLondon/event_emin_ros#2]
Hello,

Thanks for sharing such a great work!
I've set up your ROS node, and I see that you have five possible models: affinity, isometry, rotation, similarity, and translation2d.
All of them provide the vars[] output as documented in your readme. However, could you help me understand what the elements on the vector correspond to depending on the model?

Thank you!

**Comment by umgnunes** [comment]
Hi, thanks for your interest!

The elements on the vector depend on the model and follow the definition and order presented in the paper [Robust Event-based Vision Model Estimation by Dispersion Minimisation](https://ieeexplore.ieee.org/document/9625712), Section 4 Applications and Models.
